method: ardt
normalize: false
train_args:
  gamma: 1.0
  scale: 5.0
  mse_epochs: 6
  maxmin_epochs: 10
  ret_obs_act_model_args:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    batchnorm: False
    layernorm: False
    dropout: 0.0
  ret_model_args:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    batchnorm: False
    layernorm: False
    dropout: 0.0
