method: ardt
normalize: false
train_args:
  env_name: "halfcheetah"
  gamma: 1.0
  scale: 1000.
  batch_size: 512
  cluster_epochs: 40
  return_epochs: 10
  
  ret_obs_action_model:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    batchnorm: False
    layernorm: False
    dropout: 0.0
  
  obs_action_model:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    batchnorm: False
    layernorm: False
    dropout: 0.0

  return_model:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    batchnorm: False
    layernorm: False
    dropout: 0.0
